name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn pandas scikit-learn joblib

    - name: Run training script
      run: python train_model.py

    - name: Build Docker image
      run: docker build -t customer-churn-mlops .